<?php

/**
 * Class SearcherErrors
 * Класс для хранения констант ошибок
 */
class SearcherErrors
{
    const ERROR_NONE = 0;

    const SEARCH_TEXT_NOT_SET = 11;
    const LANGUAGE_NOT_SET = 12;
    const INCORRECT_SEARCH_TEXT = 13;
    const UNSUPPORTED_LANGUAGE = 14;
    const SERVICE_TYPE_NOT_SET = 15;
    const SERVICE_TYPE_INCORRECT = 16;
    const ROUTE_NOT_SET = 17;
    const SCHEDULE_NOT_SET = 18;
    const FLIGHT_CLASS_NOT_SET = 19;
    const CHARTER_ATTR_NOT_SET = 20;
    const REGULAR_ATTR_NOT_SET = 21;
    const FLEXIBLE_DAYS_NOT_SET = 22;
    const ADULT_NUM_NOT_SET = 23;
    const CHILDREN_NUM_NOT_SET = 24;
    const INFANTS_NUM_NOT_SET = 25;
    const CHILDREN_AGES_NOT_SET = 26;
    const OFFER_LIMIT_NOT_SET = 27;
    const INCORRECT_ROUTE_PARAMS = 28;
    const INCORRECT_SCHEDULE_PARAMS = 29;
    const INCORRECT_FLIGHT_CLASS = 30;
    const INCORRECT_CHARTER_VALUE = 31;
    const INCORRECT_REGULAR_VALUE = 32;
    const INCORRECT_FLEXIBLE_DAYS_VALUE = 33;
    const INCORRECT_ADULTS_NUM_VALUE = 34;
    const INCORRECT_CHILDREN_NUM_VALUE = 35;
    const INCORRECT_INFANTS_NUM_VALUE = 36;
    const INCORRECT_LIMIT_COUNT_VALUE = 37;
    const REQUEST_TOKEN_NOT_SET = 38;
    const RESPONSE_CURRENCY_NOT_SET = 39;
    const RESPONSE_LANG_NOT_SET = 40;
    const INCORRECT_REQUEST_TOKEN = 41;
    const INCORRECT_RESPONSE_CURRENCY = 42;
    const INCORRECT_RESPONSE_LANG = 43;
    const SUPPLIER_ID_NOT_SET = 44;
    const INCORRECT_SUPPLIER_ID = 45;
    const OFFER_ID_NOT_SET = 46;
    const INCORRECT_DIRECT_FLIGHT_VALUE = 47;
    const DIRECT_FLIGHT_VALUE_NOT_SET = 48;
    const FLIGHT_NUMBER_NOT_SET = 49;
    const SUPPLIER_CODE_NOT_SET = 50;
    const AIRLINE_CODES_NOT_SET = 51;
    const UNITE_OFFERS_NOT_SET = 52;
    const INCORRECT_AIRLINE_CODES = 53;
    const INCORRECT_UNITE_OFFERS_VALUE = 54;
    const INCORRECT_TRIPS_NUMBER = 55;
    const CLIENT_COMPANY_NOT_SET = 56;
    const INCORRECT_ACCOMODATION_PLACE_STRUCT = 57;
    const FREE_ONLY_PARAM_NOT_SET = 58;
    const INCORRECT_FREE_ONLY_PARAM = 59;
    const ROOMS_PARAM_NOT_SET = 60;
    const INCORRECT_ROOMS_STRUCT = 61;
    const INCORRECT_ACCOMODATION_CATEGORY = 62;
    const INCORRECT_HOTEL_FILTERS_PARAMS = 63;
    const HOTEL_FILTERS_PARAMS_NOT_SET = 64;
    const CITY_ID_NOT_SET = 65;
    const INCORRECT_CITY_ID = 66;
    const HOTEL_CODE_NOT_SET = 67;
    const HOTEL_SUPPLIER_NOT_SET = 68;
    const HOTEL_ID_KT_INCORRECT = 69;
    const HOTELS_CHAIN_NOT_SET = 70;
    const MEAL_TYPE_NOT_SET = 71;
    const INCORRECT_ACCOMMODATION_ROOMS_STRUCT = 72;
    const ORDERNUM_NOT_SET = 73;
    const DATE_START_GREATER_THAN_FINISH = 74;
    const CLIENT_COMPANY_NOT_FOUND = 75;
    const COMPANY_HAS_NO_ONLINE_MANAGERS = 76;
    const INCORRECT_INPUT_PARAMS = 77;
    const INCORRECT_TOURIST_NUMBER = 78;
    const GATE_NOT_FOUND = 79;
    const COUNTRY_NOT_FOUND = 80;
    const CITY_NOT_FOUND = 81;


    const CANNOT_GET_AIRPORT_LOCATIONS_LIST = 501;
    const CANNOT_CREATE_SEARCH_REQUEST = 502;
    const CANNOT_CREATE_ROUTE_TRIP = 503;
    const CANNOT_WRITE_TO_CACHE_SEARCH_TASK = 504;
    const CANNOT_GET_SEARCH_REQUEST_PARAMS = 505;
    const CANNOT_GET_SEARCH_REQUEST_ROUTE_PARAMS = 506;
    const CANNOT_CREATE_TRIP_SEGMENT = 507;
    const CANNOT_GET_OFFER = 508;
    const CANNOT_GET_TRIP = 509;
    const CANNOT_GET_SEGMENT = 510;
    const CANNOT_GET_SUCCESS_VALUE_FROM_CACHE_SEARCH_TASK = 511;
    const CANNOT_GET_CITIES_LOCATIONS_LIST = 512;
    const CANNOT_GET_HOTELS_LIST = 513;
    const CANNOT_CREATE_ROOM_OFFER = 514;
    const CANNOT_GET_ROOM_OFFER_PRICE = 515;
    const CANNOT_CREATE_ROOM_OFFER_PRICE = 516;
    const CANNOT_GET_ROOM_OFFER = 517;

    const INCORRECT_VALIDATION_RULES = 601;
    const INCORRECT_GATEWAYS_CONFIG = 602;
    const GPTS_CONFIG_SECTION_NOT_SET = 603;
    const TEST_API_SECTION_NOT_SET = 604;
    const PROD_API_SECTION_NOT_SET = 605;
    const INCORRECT_TEST_API_SETTINGS = 606;
    const INCORRECT_PROD_API_SETTINGS = 607;
    const CANNOT_CREATE_GEARMAN_CLIENT = 608;
    const INCORRECT_GEARMAN_CONFIG = 609;
    const INCORRECT_MODULE_NAMESPACE_CONFIG = 610;
    const METHOD_NOT_IMPLEMENTED = 611;
    const INCORRECT_PROVIDER_SETTINGS = 612;
    const INCORRECT_SUPPLIER_SETTINGS = 613;

    const CANNOT_REQUEST_OFFERS_THROUGH_GPTS = 801;
    const ERROR_REQUESTING_OFFERS = 802;
    const CANNOT_START_GEARMAN_SEARCH_TASK = 803;
}
