<?php

/**
 * Class OrderServiceModule
 * Отвечает за вызов компонентов и контроллеров,
 * использующихся при реализации внешнего restapi
 */
class OrderServiceModule extends KModule
{
    public function init()
    {
        $this->setImport(array(
            'orderService.models.*',
            'orderService.components.*',
            'orderService.components.Logger.*',
            'orderService.components.WorkflowDelegates.*',
            'orderService.modules.order.models.*',
            'orderService.modules.order.components.*',
            'orderService.models.*',
            'orderService.models.Entity.*',
            'orderService.models.Entity.Avia.*',
            'orderService.models.Entity.Hotel.*',
            'orderService.models.Entity.History.*',
            'orderService.models.Entity.Tourist.*',
            'orderService.models.Entity.Tourist.ServiceTourist.*',
            'orderService.models.Entity.AuthRule.*',
            'orderService.models.Entity.AuthRule.AuthServiceCondition.*',
            'orderService.models.Entity.ServiceAuthRule.*',
            'orderService.models.Repository.*',
            'orderService.models.OfferCreator.*',
            'orderService.models.Delegate.*',
            'orderService.models.Report.*',
            'orderService.models.Report.concreteReport.*',
            'orderService.models.Report.concreteReport.BookReport.*',
            'orderService.models.Report.specification.*',
            'orderService.models.Report.spreadsheet.*',
            'orderService.models.Report.SOReport.*',

            'orderService.components.Delegates.*',
            'orderService.components.Delegates.OWM.*',
            'orderService.components.Delegates.OWM.New.*',
            'orderService.components.Delegates.OWM.AddService.*',
            'orderService.components.Delegates.OWM.AddTourist.*',
            'orderService.components.Delegates.OWM.AddExtraService.*',
            'orderService.components.Delegates.OWM.RemoveExtraService.*',
            'orderService.components.Delegates.OWM.TouristToService.*',
            'orderService.components.Delegates.OWM.BookStart.*',
            'orderService.components.Delegates.OWM.BookComplete.*',
            'orderService.components.Delegates.OWM.BookCancel.*',
            'orderService.components.Delegates.OWM.BookChange.*',
            'orderService.components.Delegates.OWM.PayStart.*',
            'orderService.components.Delegates.OWM.PayFinish.*',
            'orderService.components.Delegates.OWM.IssueTickets.*',
            'orderService.components.Delegates.OWM.Done.*',
            'orderService.components.Delegates.OWM.Manual.*',
            'orderService.components.Delegates.OWM.ManualSetStatus.*',
            'orderService.components.Delegates.OWM.SetReservationData.*',
            'orderService.components.Delegates.OWM.SetAdditionalData.*',
            'orderService.components.Delegates.OWM.SetTickets.*',
            'orderService.components.Delegates.OWM.SetServiceData.*',
            'orderService.components.Delegates.OWM.ServiceCancel.*',
            'orderService.components.Delegates.OWM.RemoveTourist.*',
            'orderService.components.Delegates.OWM.Reprice.*',
            'orderService.components.Delegates.OWM.InvoiceCancel.*',
            'orderService.components.Delegates.OWM.Import.*',
            'orderService.components.Delegates.OWM.OrderSync.*',
            'orderService.components.Delegates.OWM.Authorization.*',

            'orderService.components.Delegates.SWM.*',
            'orderService.components.Delegates.SWM.TouristToService.*',
            'orderService.components.Delegates.SWM.Create.*',
            'orderService.components.Delegates.SWM.AddExtraService.*',
            'orderService.components.Delegates.SWM.RemoveExtraService.*',
            'orderService.components.Delegates.SWM.BookStart.*',
            'orderService.components.Delegates.SWM.BookComplete.*',
            'orderService.components.Delegates.SWM.BookCancel.*',
            'orderService.components.Delegates.SWM.BookChange.*',
            'orderService.components.Delegates.SWM.PayStart.*',
            'orderService.components.Delegates.SWM.PayFinish.*',
            'orderService.components.Delegates.SWM.IssueTickets.*',
            'orderService.components.Delegates.SWM.Done.*',
            'orderService.components.Delegates.SWM.Manual.*',
            'orderService.components.Delegates.SWM.ManualSetStatus.*',
            'orderService.components.Delegates.SWM.SetAdditionalData.*',
            'orderService.components.Delegates.SWM.SetReservationData.*',
            'orderService.components.Delegates.SWM.SetTickets.*',
            'orderService.components.Delegates.SWM.SetServiceData.*',
            'orderService.components.Delegates.SWM.OrderSync.*',
            'orderService.components.Delegates.SWM.Authorization.*',

            'orderService.modules.auth.models.*',
            'orderService.modules.auth.components.*',

            'orderService.modules.order.models.*',
            'orderService.modules.order.models.offers.*',
            'orderService.modules.order.models.services.*',
            'orderService.modules.order.models.tickets.*',
            'orderService.modules.order.components.*',

            'orderService.modules.utk.components.*',
            'orderService.modules.utk.models.*',
            'orderService.modules.utk.models.Listeners.*',
        ));
    }
}
